version: '3.5'

services:
  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
      - redis
    networks:
      - redis

  redis:
    image: "redis:latest"
    container_name: "redis"
    expose:
     - 6379
    networks:
     - redis

networks:
  redis: